version: "3.7"
services:
  db:
    image: mysql:5.7
    ports: 
      - 13306:3306
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  admin:
    image: adminer:4.7-standalone
    ports:
      - 18080:8080