version: "3.7"
services:
  zookeeper:
    image: zookeeper:3.5
    hostname: zookeeper
    ports:
      - 12181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181

  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "19092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "10.152.26.135" # local ip
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CREATE_TOPICS: "engine-vector-space-search-service:1:1"
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_LOG_RETENTION_BYTES: 1073741824 # 1G
      KAFKA_LOG_RETENTION_HOURS: 24
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock